import type { Block } from "./seo";

export type Post = {
  slug: string;
  title: string;
  excerpt: string;
  category: "Guides" | "Playbooks" | "Marketing" | "Sales" | "Payments" | "AI";
  published: string; // ISO date
  modified?: string;
  readMinutes: number;
  keywords: string[];
  /** Feature / solution pages this post should send readers to. */
  cta: { label: string; href: string };
  body: Block[];
};

export const POSTS: Post[] = [
  {
    slug: "whatsapp-business-api-vs-business-app",
    title: "WhatsApp Business API vs WhatsApp Business App: which one does your business need?",
    excerpt: "The free app is perfect on day one. Here's how to tell when you've outgrown it — and what actually changes when you move to the API.",
    category: "Guides",
    published: "2026-09-20",
    readMinutes: 6,
    keywords: ["WhatsApp Business API vs app", "WhatsApp Business API", "WhatsApp Business app limits"],
    cta: { label: "See the shared inbox", href: "/features/shared-inbox" },
    body: [
      { type: "p", text: "Most businesses start on the **WhatsApp Business app** — the free app on your phone. It's good: a business profile, labels, quick replies and a catalogue. Then the business grows and the cracks appear. This guide explains where they appear and what the **WhatsApp Business Platform** (the API) changes." },
      { type: "h2", text: "What the Business app does well" },
      { type: "ul", items: ["Free and quick to set up with a phone number", "One owner can use it on a phone and a few linked devices", "Good for a solo owner or a very small shop", "Labels, greeting and away messages, and a simple catalogue"] },
      { type: "h2", text: "Where teams outgrow it" },
      { type: "ul", items: ["**Team access.** The app isn't built for a team of agents replying from one number with individual logins and assignment.", "**Automation.** You get simple greeting and away messages, but no multi-step flows, no branching and no AI agent.", "**Campaigns.** Broadcast lists are limited to people who saved your number and can't report reliably on what happened.", "**Integrations.** Connecting your store, payments and CRM needs the API.", "**Visibility.** There's no per-agent workload, response-time reporting or sales tracking."] },
      { type: "h2", text: "What changes when you use the API" },
      { type: "p", text: "The platform is accessed through a software provider — like LeadForGrow — that gives you an inbox, flows, templates and campaigns on top. Three things work differently, and it's worth knowing them upfront:" },
      { type: "ol", items: ["**Message templates.** To start a conversation with a customer (or reply after 24 hours), you send a Meta-approved template. Replying within 24 hours of a customer's message is free-form.", "**Pricing.** Meta charges for certain message categories. Your software provider bills you separately for the platform. Check Meta's current rate card for your country.", "**Phone app.** A number connected to the Cloud API is managed through the software rather than the phone app."] },
      { type: "callout", tone: "tip", title: "A simple rule of thumb", text: "If more than one person needs to answer, or you want to send campaigns and automate replies, you've outgrown the app. If it's just you and a handful of chats a day, stay on it." },
      { type: "h2", text: "Moving over without losing customers" },
      { type: "p", text: "Plan the switch for a quiet day, export the contacts you have permission to message, and set up your welcome message, away message and top five quick replies first. Then submit the templates you'll need — order updates, reminders, follow-ups — so they're approved when you need them." },
      { type: "p", text: "You can try the whole workflow free during the trial; [connect your number](/signup) and see the inbox in minutes." },
    ],
  },
  {
    slug: "whatsapp-template-approval-guide",
    title: "How to write WhatsApp message templates that get approved the first time",
    excerpt: "Most template rejections come from the same handful of mistakes. Here's a checklist to avoid them, with examples of wording that works.",
    category: "Guides",
    published: "2026-09-20",
    readMinutes: 6,
    keywords: ["WhatsApp template approval", "WhatsApp message template examples", "WhatsApp template rejected"],
    cta: { label: "Explore the template manager", href: "/features/templates" },
    body: [
      { type: "p", text: "A message template is a pre-approved message you can send to start a conversation or to reach a customer after the 24-hour window. Meta reviews each one. Rejections cost you time, so it pays to get them right the first time." },
      { type: "h2", text: "Pick the right category" },
      { type: "table", head: ["Category", "Use it for", "Watch out for"], rows: [["Utility", "Order updates, confirmations, reminders, account alerts", "Promotional wording will get it reclassified or rejected"], ["Marketing", "Offers, launches, re-engagement", "Needs an opt-in and clear value; expect opt-outs"], ["Authentication", "One-time passwords and verification codes", "Fixed structure; don't add extra text"]] },
      { type: "h2", text: "The rejection checklist" },
      { type: "ol", items: ["**Provide real sample values** for every variable. 'Test' or 'abc' is a common reason for rejection.", "**Don't start or end with a variable.** Wrap variables in real words.", "**Don't use too many variables** for a short message.", "**Keep the tone honest.** No threats, misleading claims or requests for sensitive data.", "**Match the category** to the content — a discount code is marketing, even in a friendly 'order update'.", "**Use working links.** Shorteners that hide the destination often get flagged."] },
      { type: "h2", text: "Examples that tend to work" },
      { type: "code", lang: "text", text: "Utility — order update\nHi {{1}}, your order {{2}} has shipped and will reach you by {{3}}. Track it here: {{4}}\n\nUtility — appointment reminder\nHi {{1}}, this is a reminder of your appointment on {{2}} at {{3}}. Reply 1 to confirm or 2 to reschedule." },
      { type: "p", text: "Notice how each message is specific, has a clear purpose and asks for a simple next step." },
      { type: "h2", text: "If a template is rejected" },
      { type: "p", text: "Read the reason, edit the wording and submit a new version. In the LeadForGrow template manager the rejection reason is shown next to the template so you can fix it quickly." },
      { type: "callout", tone: "info", text: "Approval decisions are Meta's. Following the checklist improves your odds but can't guarantee them." },
    ],
  },
  {
    slug: "whatsapp-24-hour-window-explained",
    title: "The WhatsApp 24-hour window, explained: what you can send and when",
    excerpt: "Why some messages send instantly and others need a template — and how to design your workflows around the window.",
    category: "Guides",
    published: "2026-09-20",
    readMinutes: 5,
    keywords: ["WhatsApp 24 hour window", "WhatsApp customer service window", "WhatsApp session message"],
    cta: { label: "See how the inbox tracks it", href: "/features/shared-inbox" },
    body: [
      { type: "p", text: "If you've ever wondered why you can reply to some customers freely but have to send a template to others, the answer is the **24-hour customer service window**." },
      { type: "h2", text: "How the window works" },
      { type: "p", text: "Each time a customer messages your business number, a 24-hour window opens (and resets with every new message from them). While it's open you can send any type of message: text, images, documents, buttons and more. Once it closes, you can only send an approved message template." },
      { type: "ul", items: ["**Window open:** free-form replies, media, interactive messages", "**Window closed:** approved templates only", "**Click-to-WhatsApp ads:** conversations from ads can get an extended free-entry period, shown on the contact"] },
      { type: "h2", text: "Designing around it" },
      { type: "ol", items: ["**Answer quickly.** Every fast reply is a chance to solve the problem inside the window.", "**Use a follow-up template** when you need to reach out after it closes — a polite 'still interested?' with a quick-reply button is enough to reopen it.", "**Let automation hold the window open.** An away message or flow that asks a question keeps the conversation moving.", "**Show agents the countdown.** In LeadForGrow, the composer shows when the window closes and switches to templates automatically."] },
      { type: "callout", tone: "tip", title: "A good re-engagement template", text: "Hi {{1}}, we're still holding your quote for {{2}}. Would you like to go ahead? [Yes, continue] [Not now]" },
      { type: "p", text: "Design your flows so the most important information goes out while the window is open, and use templates for the moments when you must reach out first." },
    ],
  },
  {
    slug: "whatsapp-lead-qualification-flow",
    title: "A 6-step WhatsApp lead qualification flow you can build in an afternoon",
    excerpt: "Ask the right questions, tag the right people and hand over hot leads with everything collected — a playbook with the exact steps.",
    category: "Playbooks",
    published: "2026-09-20",
    readMinutes: 6,
    keywords: ["WhatsApp lead qualification", "WhatsApp chatbot flow example", "WhatsApp lead generation"],
    cta: { label: "Build it with the flow builder", href: "/features/chat-flow-builder" },
    body: [
      { type: "p", text: "Most leads don't need a salesperson in the first minute — they need a fast, friendly reply and a couple of good questions. Here's a flow that does that, and gets the right people to your team." },
      { type: "h2", text: "The six steps" },
      { type: "ol", items: ["**Trigger** on a keyword ('demo', 'price') or any first message.", "**Greet by name** and set expectations: 'Two quick questions and I'll get the right person for you.'", "**Ask what they need** with a list menu (up to ten options) so answers are clean.", "**Ask for the key detail** — budget, city, quantity or timeline — with validation for numbers and choices.", "**Branch:** high intent goes to a salesperson; the rest gets helpful resources and a reminder later.", "**Create a deal** and assign an owner so nothing sits unowned."] },
      { type: "h2", text: "What to tag and save" },
      { type: "ul", items: ["Save answers as contact details (`budget`, `city`) so campaigns can use them later", "Add a tag like `hot-lead` or `interest-pricing`", "Keep the source — ads, widget or QR — on the contact"] },
      { type: "h2", text: "Handling silence" },
      { type: "p", text: "Add a **wait step** of a day and a gentle follow-up template. If they answer, the flow continues; if not, the deal stays in your first stage so you can see it in the pipeline." },
      { type: "callout", tone: "warn", title: "Don't over-ask", text: "Every extra question loses people. Start with two, look at where they drop off in the run log, and add only what your sales team truly uses." },
      { type: "p", text: "Once published, the flow runs on every matching message. Watch the first few runs in the execution log, then refine the wording." },
    ],
  },
  {
    slug: "recover-abandoned-carts-on-whatsapp",
    title: "How to recover abandoned carts on WhatsApp without being annoying",
    excerpt: "Timing, tone and one clear next step: a practical approach to cart recovery that respects your customers.",
    category: "Playbooks",
    published: "2026-09-20",
    readMinutes: 5,
    keywords: ["abandoned cart WhatsApp", "cart recovery WhatsApp", "Shopify abandoned checkout WhatsApp"],
    cta: { label: "E-commerce on WhatsApp", href: "/solutions/ecommerce" },
    body: [
      { type: "p", text: "Cart recovery works on WhatsApp because it feels like a personal message rather than a promotion. It also fails quickly if it feels like spam. Here's how to keep it on the right side of that line." },
      { type: "h2", text: "Get permission first" },
      { type: "p", text: "Only message customers who opted in to WhatsApp updates at checkout. A clear checkbox — 'Send my order updates on WhatsApp' — protects your quality rating and your reputation." },
      { type: "h2", text: "Timing" },
      { type: "ul", items: ["**About an hour after abandonment:** a helpful nudge — 'Need help finishing your order?'", "**Next day:** a short reminder with the product name and the checkout link", "**Then stop.** Two messages is plenty."] },
      { type: "h2", text: "What to write" },
      { type: "code", lang: "text", text: "Hi {{1}}, you left {{2}} in your cart. Want us to hold it for you? Complete your order here: {{3}}" },
      { type: "ul", items: ["Name the product so it's recognisable", "One link, one action", "Offer help, not pressure — a discount isn't always needed"] },
      { type: "h2", text: "How to set it up" },
      { type: "ol", items: ["Connect Shopify or WooCommerce so the 'checkout abandoned' event arrives.", "Map the event to an approved utility or marketing template.", "Add a wait step in a flow if you want a delayed second message.", "Let replies land in the shared inbox so a human can answer questions."] },
      { type: "p", text: "Measure recovered orders against messages sent and adjust the wording before adding more steps." },
    ],
  },
  {
    slug: "whatsapp-broadcast-best-practices",
    title: "WhatsApp broadcast best practices: opt-ins, timing and protecting your quality rating",
    excerpt: "Campaigns that people welcome — and that keep your number in good standing with WhatsApp.",
    category: "Marketing",
    published: "2026-09-20",
    readMinutes: 6,
    keywords: ["WhatsApp broadcast best practices", "WhatsApp marketing opt-in", "WhatsApp quality rating"],
    cta: { label: "Explore broadcasts", href: "/features/broadcasts" },
    body: [
      { type: "p", text: "A WhatsApp campaign lands in the same place as a message from a friend. That's its power — and why the rules are strict. These practices help you get results while staying in good standing." },
      { type: "h2", text: "1. Collect opt-in properly" },
      { type: "ul", items: ["Ask at checkout, on forms or in a first chat — clearly, and with the purpose stated", "Store where and when consent was given", "Never message purchased lists"] },
      { type: "h2", text: "2. Send fewer, better messages" },
      { type: "p", text: "Segment by what people did, not who they are: recent buyers, people who asked about a product, customers who haven't ordered in 60 days. Relevance is the biggest driver of read and reply rates." },
      { type: "h2", text: "3. Time it sensibly" },
      { type: "p", text: "Send when your customers are awake and likely to act — usually mid-morning or early evening in their time zone — and schedule campaigns rather than sending at midnight." },
      { type: "h2", text: "4. Make opting out effortless" },
      { type: "p", text: "Customers who reply STOP are automatically excluded from future campaigns. Make that visible in your template footer. Fewer blocks and reports mean a healthier quality rating." },
      { type: "h2", text: "5. Read the report, then follow up" },
      { type: "p", text: "Look at delivered, read and replied — not just sent. Failures carry a reason: an invalid number, a customer who hasn't accepted WhatsApp's terms or a rate limit. Fix the cause before the next send." },
      { type: "callout", tone: "info", text: "WhatsApp can limit messaging if many recipients block or report your number. Quality and relevance protect your ability to send." },
    ],
  },
  {
    slug: "build-a-whatsapp-sales-pipeline",
    title: "How to build a sales pipeline for WhatsApp leads: stages, probabilities and forecasting",
    excerpt: "Design stages that mirror how you sell, give each a win probability and finally trust your forecast.",
    category: "Sales",
    published: "2026-09-20",
    readMinutes: 6,
    keywords: ["WhatsApp sales pipeline", "sales pipeline stages", "weighted pipeline forecast", "WhatsApp CRM"],
    cta: { label: "See the sales pipeline", href: "/features/sales-pipeline" },
    body: [
      { type: "p", text: "A pipeline turns a pile of chats into something you can manage. The trick is to keep it simple enough that your team actually uses it." },
      { type: "h2", text: "Start with 4–6 stages" },
      { type: "ol", items: ["**New lead** — someone has messaged you", "**Contacted** — a person has replied", "**Qualified** — budget, need and timeline fit", "**Proposal sent** — quote or plan shared", "**Won** — money collected or contract signed", "**Lost** — with a reason"] },
      { type: "p", text: "Name stages after what the *customer* has done, not what you have done. It's easier to agree on and harder to game." },
      { type: "h2", text: "Give each stage a win probability" },
      { type: "p", text: "Look at your last 30 closed deals. What fraction of deals that reached each stage were eventually won? Use those numbers, even if rough. The **weighted forecast** is each open deal's value multiplied by its stage probability — a far more honest figure than the raw total." },
      { type: "table", head: ["Stage", "Example probability", "Value of ₹1,00,000 deal"], rows: [["New lead", "10%", "₹10,000"], ["Qualified", "50%", "₹50,000"], ["Proposal sent", "75%", "₹75,000"]] },
      { type: "h2", text: "Automate the boring parts" },
      { type: "ul", items: ["Create deals automatically for new WhatsApp contacts", "Move a deal when a flow qualifies the lead", "Send a payment link from the deal and record the payment"] },
      { type: "h2", text: "Review weekly" },
      { type: "p", text: "In the sales report, look at win rate, average deal size, time to close and the reasons deals are lost. If most losses say 'price', the fix is in your proposal stage, not your ads." },
    ],
  },
  {
    slug: "collect-payments-on-whatsapp-with-razorpay",
    title: "How to collect payments on WhatsApp with Razorpay payment links",
    excerpt: "A step-by-step walkthrough: connect your Razorpay account, send a link inside a chat and let your deal update itself.",
    category: "Payments",
    published: "2026-09-20",
    readMinutes: 5,
    keywords: ["Razorpay payment link WhatsApp", "collect payment WhatsApp India", "UPI payment link", "Razorpay payment links"],
    cta: { label: "Payments on WhatsApp", href: "/features/payments" },
    body: [
      { type: "p", text: "When a customer says 'yes, I'll take it', the fastest way to close is to let them pay right there. Razorpay payment links make that a single message." },
      { type: "h2", text: "Set up in three steps" },
      { type: "ol", items: ["In your Razorpay Dashboard, open **Account & Settings → API keys** and generate a Key ID and Secret. Start with **test mode** keys to try it safely.", "In LeadForGrow, go to **Settings → Payments**, paste the keys and choose **Verify & connect**. Keys are stored encrypted.", "Open a chat or a deal and choose **Request payment**. Enter the amount and what it's for."] },
      { type: "h2", text: "What happens next" },
      { type: "ul", items: ["A payment link is created on **your** Razorpay account", "You can add it straight into your reply with a friendly message", "The customer pays by UPI, card or netbanking", "The link flips to **paid** in LeadForGrow and the deal records it"] },
      { type: "callout", tone: "tip", title: "Automate it", text: "Add a **Payment link** step to a flow so qualified customers automatically receive a link, and use the *payment received* event to trigger a thank-you message." },
      { type: "h2", text: "Good habits" },
      { type: "ul", items: ["Put the purpose in the description so the customer sees exactly what they're paying for", "Set an expiry that fits the offer — 24 hours for a limited slot, 7 days for an invoice", "Cancel unpaid links you no longer need"] },
      { type: "p", text: "Razorpay's fees apply to the payments you collect on your own account; LeadForGrow doesn't add a fee on them." },
    ],
  },
  {
    slug: "ai-agent-vs-rule-based-flows",
    title: "AI agent or rule-based flow? How to choose on WhatsApp",
    excerpt: "Both have a place. Use flows for processes that must go a certain way and AI for questions you can't predict.",
    category: "AI",
    published: "2026-09-20",
    readMinutes: 5,
    keywords: ["AI chatbot vs rule-based chatbot", "WhatsApp AI agent", "WhatsApp chatbot best practices"],
    cta: { label: "Meet the AI agent", href: "/features/ai-agent" },
    body: [
      { type: "p", text: "The choice isn't AI versus flows — it's knowing which one to reach for. They're good at different things." },
      { type: "h2", text: "Use a rule-based flow when…" },
      { type: "ul", items: ["The process has **fixed steps** — booking, KYC, order intake", "You need **validated data** — a date, a number, an email", "You must **guarantee the wording**, like consent or pricing", "You want to **trigger actions** — create a deal, assign an agent, send a payment link"] },
      { type: "h2", text: "Use the AI agent when…" },
      { type: "ul", items: ["Customers ask **open questions** about policies, products or timings", "The answer already exists in your **FAQs or website**", "You'd like to **cover after-hours** messages", "The volume of repetitive questions is high"] },
      { type: "h2", text: "Combine them" },
      { type: "p", text: "The strongest set-ups let a flow handle the structured journey and call the AI for the open-ended moments. For example: a menu offers 'Book a demo' (flow) and 'Ask a question' (AI). The AI answers from your knowledge base; if it can't, it hands the conversation to a human." },
      { type: "callout", tone: "warn", title: "Keep a human in the loop", text: "Read AI conversations regularly and treat gaps you find as a to-do list for your knowledge base. Make hand-over easy and obvious." },
      { type: "p", text: "Start small: enable the AI for a single kind of question, review results for a week, then widen its scope." },
    ],
  },
];

export const postBySlug = (slug: string) => POSTS.find((p) => p.slug === slug);
export const CATEGORIES = ["Guides", "Playbooks", "Marketing", "Sales", "Payments", "AI"] as const;
