import { BarChart3, Bell, Bot, Brain, CalendarClock, Clock, CreditCard, FileText, Filter, GitBranch, Globe, Handshake, Inbox, KeyRound, Layers, LayoutGrid, Link2, Lock, Megaphone, MessageSquareReply, MousePointerClick, Plug, QrCode, Receipt, Route, ScanSearch, Send, ShieldCheck, Sparkles, Tag, Target, TrendingUp, UserCheck, Users, Webhook, Workflow, Zap, type LucideIcon } from "lucide-react";
import type { Faq } from "./seo";

export type VisualKind = "inbox" | "broadcast" | "flow" | "ai" | "replies" | "pipeline" | "payments" | "widget" | "templates" | "analytics" | "integrations";

export type Feature = {
  slug: string;
  navLabel: string;
  icon: LucideIcon;
  /** One line used in menus and cards. */
  tagline: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  h1: string;
  lead: string;
  visual: VisualKind;
  benefits: { icon: LucideIcon; title: string; body: string }[];
  steps: { title: string; body: string }[];
  useCases: { title: string; body: string }[];
  faqs: Faq[];
  related: string[];
};

export const FEATURES: Feature[] = [
  {
    slug: "shared-inbox",
    navLabel: "Shared Team Inbox",
    icon: Inbox,
    tagline: "One WhatsApp number, your whole team, zero chaos",
    metaTitle: "Shared Team Inbox for WhatsApp Business",
    metaDescription: "Let your whole team answer customers from one WhatsApp Business number. Assign chats, leave private notes, use quick replies and never miss the 24-hour window.",
    keywords: ["WhatsApp shared inbox", "WhatsApp team inbox", "WhatsApp multi-agent", "WhatsApp CRM inbox"],
    h1: "A shared inbox that keeps every WhatsApp conversation owned",
    lead: "Stop passing a phone around. Everyone on your team replies from one WhatsApp Business number, chats are assigned to a person, and nothing gets answered twice — or not at all.",
    visual: "inbox",
    benefits: [
      { icon: Users, title: "Assign and route automatically", body: "Round-robin or fixed rules hand every new chat to an available teammate, so the first reply never waits on someone to notice it." },
      { icon: Clock, title: "Live 24-hour window tracking", body: "See exactly how long you can reply freely. When the window closes, the composer switches to approved templates so you never hit a blocked send." },
      { icon: MessageSquareReply, title: "Quick replies with a slash", body: "Type / and pick a saved answer. Consistent, fast replies for pricing, hours, delivery times and everything you type ten times a day." },
      { icon: Tag, title: "Labels, tags and private notes", body: "Label a conversation, tag the contact and leave notes only your team can see — full context for whoever picks the chat up next." },
      { icon: Bot, title: "Bot first, human when it matters", body: "Let flows and the AI agent handle the routine. The moment a person replies, automation pauses so customers never get talked over." },
      { icon: Handshake, title: "Deals beside the conversation", body: "Open the contact panel to see their deals, add a new one and request a payment without leaving the chat." },
    ],
    steps: [
      { title: "Connect your number", body: "Link your WhatsApp Business number through Meta's Cloud API in a few minutes." },
      { title: "Invite your team", body: "Add agents and admins with roles, then choose how new chats are assigned." },
      { title: "Reply together", body: "Work from one inbox with filters for open, mine, unassigned and resolved conversations." },
      { title: "Measure and improve", body: "Track first-response time and workload per agent in conversation analytics." },
    ],
    useCases: [
      { title: "Support desks", body: "Route by workload, resolve conversations and keep a clean history for repeat customers." },
      { title: "Sales teams", body: "Give each lead an owner, keep notes on the deal and follow up inside the same thread." },
      { title: "Clinics and service businesses", body: "Front-desk staff share one number while doctors or technicians are looped in with internal notes." },
    ],
    faqs: [
      { q: "How many people can use one WhatsApp number?", a: "As many seats as your plan includes. Every seat signs in with its own login, so each reply is attributed to the right person." },
      { q: "Can customers tell that several agents are replying?", a: "No. Customers see a single business number and name. Internally you see who sent each message." },
      { q: "What happens after the 24-hour window closes?", a: "WhatsApp only allows free-form replies within 24 hours of the customer's last message. After that, the inbox lets you send an approved message template to restart the conversation." },
      { q: "Can I keep the WhatsApp Business app on my phone?", a: "Numbers on the WhatsApp Cloud API run through the platform rather than the phone app. You reply from the LeadForGrow inbox on any device with a browser." },
    ],
    related: ["auto-replies", "chat-flow-builder", "sales-pipeline"],
  },
  {
    slug: "broadcasts",
    navLabel: "WhatsApp Broadcasts",
    icon: Megaphone,
    tagline: "Campaigns that reach the right people, with proof they landed",
    metaTitle: "WhatsApp Broadcast Campaigns with Delivery Reports",
    metaDescription: "Send approved WhatsApp template campaigns to tags, segments or uploaded lists. Schedule them, respect opt-outs and see delivered, read and replied per recipient.",
    keywords: ["WhatsApp broadcast", "WhatsApp bulk messaging", "WhatsApp marketing campaigns", "WhatsApp template messages"],
    h1: "WhatsApp broadcasts with delivery you can actually verify",
    lead: "Pick an approved template, choose who should get it and send now or later. Every recipient gets a status — sent, delivered, read, replied or failed with a reason — so you know what really happened.",
    visual: "broadcast",
    benefits: [
      { icon: Target, title: "Audiences that stay current", body: "Send to everyone, a tag, a saved segment, an uploaded CSV or a pasted list of numbers. Segments update as your contacts change." },
      { icon: CalendarClock, title: "Schedule for the right moment", body: "Queue a campaign for tomorrow morning in your time zone. The scheduler sends it without anyone needing to be online." },
      { icon: ShieldCheck, title: "Opt-outs are honoured", body: "Contacts who reply STOP are excluded automatically, protecting your quality rating and your customers' trust." },
      { icon: BarChart3, title: "Per-recipient reporting", body: "Delivered, read, replied and failed counts per campaign, with the failure reason for every message that did not go through." },
      { icon: FileText, title: "Personalised with variables", body: "Map template variables to contact fields — name, city or any custom detail — so each message reads like it was written for one person." },
      { icon: Filter, title: "Preview before you commit", body: "See exactly how many people will receive a campaign, and how many were skipped and why, before you press send." },
    ],
    steps: [
      { title: "Choose an approved template", body: "Templates approved by Meta are available to broadcast; drafts and rejected ones are not." },
      { title: "Pick your audience", body: "Tags, segments, CSV uploads or pasted numbers — with a live count and skipped-contact breakdown." },
      { title: "Send or schedule", body: "Start immediately or set a date and time. Pause or cancel while it is running." },
      { title: "Read the report", body: "Track delivery, reads and replies, then follow up with the people who responded." },
    ],
    useCases: [
      { title: "Order and delivery updates", body: "Transactional templates go out the moment an order changes state, straight from your store." },
      { title: "Offers and launches", body: "Announce a sale to the customers who bought a related product last quarter." },
      { title: "Renewals and reminders", body: "Nudge customers before a subscription, appointment or fee is due." },
    ],
    faqs: [
      { q: "Do I need Meta-approved templates to broadcast?", a: "Yes. WhatsApp requires an approved message template to start a conversation outside the 24-hour window. You create and submit templates from inside the dashboard and see their approval status." },
      { q: "Does WhatsApp charge per message?", a: "Meta charges for template messages according to its published pricing for your country and message category. Those charges are billed by Meta separately from your LeadForGrow plan." },
      { q: "Can I send to contacts I uploaded from a spreadsheet?", a: "Yes, as long as you have their permission to contact them on WhatsApp. We recommend recording opt-in and honouring opt-outs, which the platform does automatically." },
      { q: "How fast do campaigns send?", a: "Messages are sent in a controlled stream that respects Meta's rate limits. Large campaigns take longer, and progress is visible live in the report." },
    ],
    related: ["templates", "analytics", "auto-replies"],
  },
  {
    slug: "chat-flow-builder",
    navLabel: "No-code Chat Flows",
    icon: Workflow,
    tagline: "Design conversations on a canvas, publish in one click",
    metaTitle: "No-code WhatsApp Chatbot & Flow Builder",
    metaDescription: "Build WhatsApp chat flows without code: buttons, list menus, questions with validation, conditions, delays, tags, webhooks, deals and payment links — then publish in one click.",
    keywords: ["WhatsApp chatbot builder", "no-code WhatsApp flow builder", "WhatsApp automation workflow", "WhatsApp lead qualification"],
    h1: "Build WhatsApp chat flows on a visual canvas",
    lead: "Drag steps onto a canvas, connect them and publish. Ask questions, validate answers, branch on what the customer says, wait, tag, call your systems, create deals and send payment links — all without writing code.",
    visual: "flow",
    benefits: [
      { icon: Route, title: "Buttons, lists and questions", body: "Send up to three quick-reply buttons or a ten-row list menu, or ask an open question and validate the answer as an email, number, date or choice." },
      { icon: GitBranch, title: "Branch on anything", body: "Route by a button tap, an answer, a tag, a saved detail or a keyword. Every branch is visible on the canvas." },
      { icon: Clock, title: "Wait, then follow up", body: "Pause for minutes, hours or days, then continue — state is stored, so restarts and deploys never lose a running conversation." },
      { icon: Webhook, title: "Talk to your own systems", body: "Call a webhook with the contact and collected answers, and use fields from the response in later messages." },
      { icon: Handshake, title: "Sales steps built in", body: "Create a deal, move it to the next stage or send a payment link as steps in the same flow that qualified the lead." },
      { icon: ShieldCheck, title: "Safe to publish", body: "Publishing checks for missing text, unreachable steps and loops that never wait. Unpublish to stop running conversations instantly." },
    ],
    steps: [
      { title: "Pick a trigger", body: "Start on a keyword, any incoming message, a new contact, a campaign reply, an event from your store or manually." },
      { title: "Add steps", body: "Drop messages, questions, conditions and actions onto the canvas and connect them." },
      { title: "Test on a real number", body: "Run the flow against a contact and watch each step execute in the run log." },
      { title: "Publish", body: "One click makes the flow live. Edit a draft freely without affecting the published version." },
    ],
    useCases: [
      { title: "Lead qualification", body: "Ask budget, timeline and city; tag hot leads; assign a salesperson and create a deal automatically." },
      { title: "Order support", body: "Let customers pick 'Where is my order?', collect the order number and call your tracking API." },
      { title: "Appointment intake", body: "Collect name, preferred date and reason, then hand over to the front desk with everything filled in." },
    ],
    faqs: [
      { q: "Do I need to know how to code?", a: "No. Flows are built visually. Coding is only needed if you choose to call your own API with the webhook step." },
      { q: "What happens if a customer stops answering?", a: "The conversation waits for the reply. You can add a wait step followed by a reminder, and unpublishing a flow cancels anything still waiting." },
      { q: "Can a flow hand over to a human?", a: "Yes. A hand-over step stops automation for that conversation, optionally tells the customer a teammate is coming, and notifies your team." },
      { q: "How many flows can I run?", a: "The number of flows depends on your plan and is shown on the pricing page. Drafts you are still working on count toward it." },
    ],
    related: ["auto-replies", "ai-agent", "sales-pipeline"],
  },
  {
    slug: "ai-agent",
    navLabel: "AI Agent",
    icon: Bot,
    tagline: "Answers from your own knowledge base, hands over when unsure",
    metaTitle: "AI Agent for WhatsApp Customer Support",
    metaDescription: "Train an AI agent on your FAQs, documents and website. It answers customers on WhatsApp in your tone, cites only your knowledge and hands over to a human when it is unsure.",
    keywords: ["WhatsApp AI chatbot", "AI customer support WhatsApp", "AI agent WhatsApp Business", "knowledge base chatbot"],
    h1: "An AI agent that answers from your knowledge — and knows when to stop",
    lead: "Add your FAQs, policies and web pages. The agent replies to customers on WhatsApp using only what you gave it, in the tone you choose, and hands the chat to your team when it can't help.",
    visual: "ai",
    benefits: [
      { icon: Brain, title: "Grounded in your content", body: "Answers are drawn from the knowledge sources you add — text, FAQs and web pages — so it talks about your business, not the internet." },
      { icon: UserCheck, title: "Human hand-over", body: "When a question is outside its knowledge or the customer asks for a person, the agent stops and routes the chat to your team." },
      { icon: Sparkles, title: "Your tone, your rules", body: "Set the personality and add instructions — formal or friendly, short or detailed, language preferences — per workspace or per flow step." },
      { icon: ScanSearch, title: "Fast, relevant retrieval", body: "Content is indexed for search so the agent finds the right passage quickly, even in a long knowledge base." },
      { icon: Lock, title: "You control the key", body: "Bring your own Anthropic API key or use the platform's, with a monthly reply allowance shown in your usage." },
      { icon: Route, title: "Works inside flows", body: "Drop an AI reply step into any flow — for example after a menu — and continue the journey once it has answered." },
    ],
    steps: [
      { title: "Add knowledge", body: "Paste text, add FAQs or point at a web page. Each source is processed and shows its status." },
      { title: "Set the tone", body: "Choose personality and any extra instructions for how the agent should respond." },
      { title: "Turn it on", body: "Enable the agent for your workspace, or use it selectively inside flows." },
      { title: "Review and refine", body: "Read the conversations, fix gaps in your knowledge base and watch hand-overs decline." },
    ],
    useCases: [
      { title: "After-hours answers", body: "Cover nights and weekends with accurate answers and a clean hand-over in the morning." },
      { title: "Repetitive questions", body: "Return policy, delivery times, fees, timings — answered instantly so agents handle the exceptions." },
      { title: "Product discovery", body: "Help visitors find the right plan or product, then pass warm leads into your pipeline." },
    ],
    faqs: [
      { q: "Can the AI make things up?", a: "The agent is instructed to answer only from your knowledge base and to hand over when it is not confident. No AI is perfect, so we recommend reviewing conversations regularly and keeping your knowledge base up to date." },
      { q: "Which model powers the agent?", a: "The agent uses Anthropic's Claude models. Your messages are sent to Anthropic only when the AI agent is enabled and needs to answer." },
      { q: "Does it work in Hindi or other languages?", a: "It replies in the language the customer writes in, as far as the underlying model supports it. Keep your knowledge base in the languages you want strong answers in." },
      { q: "Is there a limit on AI replies?", a: "Each plan includes a monthly number of AI replies. Your usage is visible in the dashboard." },
    ],
    related: ["chat-flow-builder", "shared-inbox", "auto-replies"],
  },
  {
    slug: "auto-replies",
    navLabel: "Auto-Replies",
    icon: MessageSquareReply,
    tagline: "Welcome, away and keyword replies that run 24/7",
    metaTitle: "WhatsApp Auto-Replies: Welcome, Away & Keyword",
    metaDescription: "Set up WhatsApp welcome messages, away replies for outside business hours, delayed holding replies and keyword-triggered custom replies — live in minutes.",
    keywords: ["WhatsApp auto reply", "WhatsApp away message", "WhatsApp welcome message", "WhatsApp keyword reply"],
    h1: "Auto-replies that greet, reassure and answer — around the clock",
    lead: "Greet new customers, tell people when you're closed, apologise when a reply is slow and answer common keywords instantly. Set it once and it runs every day.",
    visual: "replies",
    benefits: [
      { icon: Sparkles, title: "Welcome message", body: "A friendly first message the first time someone writes in — sent once, not on every visit." },
      { icon: Clock, title: "Away message with business hours", body: "Define your weekly hours and time zone. Outside them, customers get a clear message about when to expect a reply." },
      { icon: Bell, title: "Delayed holding reply", body: "If nobody has answered within a few minutes, send a polite note so the customer knows they haven't been forgotten." },
      { icon: MousePointerClick, title: "Custom keyword replies", body: "Reply to exact words, phrases that contain a keyword, or anything at all — checked in that order of priority." },
      { icon: Workflow, title: "Start a flow from a keyword", body: "A keyword can answer with text or launch a full chat flow when the answer needs a conversation." },
      { icon: UserCheck, title: "Stops when a human steps in", body: "Once an agent replies, automation for that chat pauses until it is resumed, so customers never get two voices." },
    ],
    steps: [
      { title: "Write your messages", body: "Welcome, away and delayed replies, using merge fields like the customer's first name." },
      { title: "Set business hours", body: "Choose days, hours and your time zone." },
      { title: "Add keyword replies", body: "Create exact, contains or catch-all replies and attach a flow if you need one." },
      { title: "Switch it on", body: "Toggle each automation independently and change it any time." },
    ],
    useCases: [
      { title: "Shops and restaurants", body: "Send timings, menu links and delivery areas the moment someone says 'menu' or 'timing'." },
      { title: "Services and agencies", body: "Acknowledge every enquiry instantly and promise a specific reply window." },
      { title: "Schools and institutes", body: "Answer admission and fee questions outside office hours." },
    ],
    faqs: [
      { q: "Will the away message send to everyone who writes after hours?", a: "It is rate-limited per customer, so someone who sends five messages after hours doesn't get five identical replies." },
      { q: "Can I use the customer's name in a reply?", a: "Yes. Use merge fields such as {{first_name}} and {{name}}, and custom fields you have saved on the contact." },
      { q: "What if two keyword replies match?", a: "Exact matches win over 'contains' matches, which win over catch-all replies, so the most specific answer is always sent." },
      { q: "Do auto-replies count against my AI allowance?", a: "No. Welcome, away, delayed and keyword replies are rule-based and don't use AI replies." },
    ],
    related: ["chat-flow-builder", "shared-inbox", "ai-agent"],
  },
  {
    slug: "sales-pipeline",
    navLabel: "Sales Pipeline",
    icon: Handshake,
    tagline: "Turn conversations into deals you can forecast",
    metaTitle: "WhatsApp Sales Pipeline & Lightweight CRM",
    metaDescription: "Track every WhatsApp lead through a drag-and-drop pipeline. Auto-create deals from new chats, log activity, forecast revenue and see win rate — all next to your inbox.",
    keywords: ["WhatsApp CRM", "WhatsApp sales pipeline", "WhatsApp lead management", "WhatsApp deal tracking"],
    h1: "A sales pipeline that lives where your leads already are",
    lead: "Every WhatsApp lead can become a deal on a drag-and-drop board. Move it through your stages, log notes, collect payment and see what you'll close this month — without exporting to another tool.",
    visual: "pipeline",
    benefits: [
      { icon: Layers, title: "A board you can shape", body: "Start with New lead → Won or design your own stages, colours and win probabilities. Won and Lost stages close deals automatically." },
      { icon: Zap, title: "Deals create themselves", body: "Turn on auto-create and every new WhatsApp contact lands in your first stage. Or create deals from a flow once a lead qualifies." },
      { icon: TrendingUp, title: "Forecast you can trust", body: "Pipeline value is weighted by each stage's win probability, so the number reflects reality rather than optimism." },
      { icon: Receipt, title: "Full activity trail", body: "Stage moves, notes, value changes and payments are logged with who did what and when." },
      { icon: BarChart3, title: "Sales reports", body: "Revenue won per day, win rate, average deal size, sales cycle, a team leaderboard and why deals are lost." },
      { icon: CreditCard, title: "Get paid in the deal", body: "Send a payment link from the deal. When it's paid, the deal records it and your flows can react." },
    ],
    steps: [
      { title: "Set your stages", body: "Keep the defaults or rename, reorder and recolour them to match how you sell." },
      { title: "Capture leads", body: "Add deals manually, auto-create from new chats or create them inside a flow." },
      { title: "Work the board", body: "Drag cards between stages, assign owners, set expected close dates and add notes." },
      { title: "Review the numbers", body: "Open Sales reports to see revenue, conversion and where deals stall." },
    ],
    useCases: [
      { title: "Inbound lead handling", body: "Ad-driven enquiries arrive as deals in New lead with the ad source attached to the contact." },
      { title: "High-ticket sales", body: "Track proposals and follow-ups for admissions, real estate, B2B software or services." },
      { title: "Agency retainers", body: "Follow a client from first chat to signed retainer, with payments collected in the same thread." },
    ],
    faqs: [
      { q: "Is this a full CRM?", a: "It's a focused pipeline built for WhatsApp-led selling: contacts, deals, stages, owners, notes, reports and payments. If you need a full CRM, connect yours through webhooks and the API." },
      { q: "Can multiple people see the same pipeline?", a: "Yes. Everyone in the workspace sees the board; agents can move and edit deals, and owners or admins configure the stages." },
      { q: "Can I export my deals?", a: "Yes. Export all deals to CSV from the pipeline page." },
      { q: "What currency are deals in?", a: "Deals default to Indian Rupees. Values are stored precisely, in paise, so totals never drift." },
    ],
    related: ["payments", "chat-flow-builder", "shared-inbox"],
  },
  {
    slug: "payments",
    navLabel: "Payments on WhatsApp",
    icon: CreditCard,
    tagline: "Collect UPI, card and netbanking payments in the chat",
    metaTitle: "Collect Payments on WhatsApp with Razorpay",
    metaDescription: "Connect your Razorpay account and send payment links inside WhatsApp chats and deals. Customers pay by UPI, card or netbanking and you see the status update live.",
    keywords: ["WhatsApp payment link", "Razorpay WhatsApp", "collect payment on WhatsApp", "UPI payment link WhatsApp"],
    h1: "Ask for payment in the same chat where the customer said yes",
    lead: "Connect your own Razorpay account and send a payment link from any conversation or deal. Your customer pays by UPI, card or netbanking; the money settles straight to you and the deal updates itself.",
    visual: "payments",
    benefits: [
      { icon: Link2, title: "Links in one click", body: "Choose an amount and description, and a Razorpay payment link drops into your reply — pre-filled for the contact." },
      { icon: Lock, title: "Your account, your money", body: "Payments settle directly into your Razorpay account. We store your keys encrypted and never touch the funds." },
      { icon: Bell, title: "Status without refreshing", body: "Links flip to paid automatically, using Razorpay's webhook or our background check if you haven't set one up." },
      { icon: Handshake, title: "Attached to deals", body: "A payment on a link created from a deal is recorded in that deal's activity trail." },
      { icon: Zap, title: "Trigger follow-ups", body: "A payment received event can start a flow — send a thank-you, an onboarding message or an invoice." },
      { icon: Receipt, title: "Clean records", body: "See every link you've sent, who it was for, whether it's paid, and cancel unpaid links in a click." },
    ],
    steps: [
      { title: "Connect Razorpay", body: "Paste your Key ID and Secret in Settings → Payments. Keys are verified before they are saved." },
      { title: "Send a link", body: "Use Request payment in a chat or on a deal, or add a Payment link step to a flow." },
      { title: "Customer pays", body: "They open the link and pay with the method they prefer." },
      { title: "You're notified", body: "The link turns paid, the deal records it and any flow waiting on it can continue." },
    ],
    useCases: [
      { title: "Advance and booking amounts", body: "Confirm a slot or an order the moment the customer pays." },
      { title: "Invoices and dues", body: "Send a link for an outstanding amount right after a reminder." },
      { title: "Course and service fees", body: "Close admissions or subscriptions without moving the customer to another channel." },
    ],
    faqs: [
      { q: "Do I need my own Razorpay account?", a: "Yes. Payment links are created on your Razorpay account so funds settle directly to you. You can start with test keys to try it safely." },
      { q: "Does LeadForGrow take a cut of my customer payments?", a: "No. Razorpay charges you its standard fees on your account; we do not add a fee on payments you collect from your customers." },
      { q: "Can customers pay by UPI?", a: "Yes. Razorpay's payment page supports UPI, cards, netbanking and wallets, depending on what is enabled on your account." },
      { q: "How do I pay for my LeadForGrow plan?", a: "Plans are paid online with Razorpay — UPI, cards or netbanking — and every payment gets a GST invoice you can download." },
    ],
    related: ["sales-pipeline", "chat-flow-builder", "integrations-api"],
  },
  {
    slug: "website-widget",
    navLabel: "Website Chat Widget",
    icon: LayoutGrid,
    tagline: "Turn website visitors into WhatsApp conversations",
    metaTitle: "WhatsApp Chat Widget for Your Website",
    metaDescription: "Add a floating WhatsApp button to any website with one script tag. Capture leads before they chat, lock it to your domains and track opens, clicks and leads.",
    keywords: ["WhatsApp chat widget", "WhatsApp website button", "click to chat WhatsApp", "WhatsApp lead capture"],
    h1: "A WhatsApp button that turns visitors into conversations",
    lead: "Paste one line of code and your site gets a branded WhatsApp chat button. Optionally capture a visitor's name and number first, so even people who never send a message become leads.",
    visual: "widget",
    benefits: [
      { icon: Globe, title: "One script, any website", body: "Works on WordPress, Shopify, Webflow, custom sites — anywhere you can add a script tag." },
      { icon: Sparkles, title: "Branded and configurable", body: "Set the colour, position, title, welcome text, call-to-action and how long to wait before it appears." },
      { icon: UserCheck, title: "Capture leads first", body: "Ask for a name and number before opening WhatsApp, and the lead lands in your contacts even if the chat never starts." },
      { icon: Lock, title: "Lock it to your domains", body: "Restrict the widget to the domains you own so it can't be copied to other sites." },
      { icon: BarChart3, title: "See what it does", body: "Track how often it opens, is clicked and produces a lead." },
      { icon: QrCode, title: "QR code for print", body: "Generate a QR code that opens the same conversation for posters, packaging and storefronts." },
    ],
    steps: [
      { title: "Create a widget", body: "Pick the number visitors should message and customise how it looks." },
      { title: "Copy the snippet", body: "Paste the script tag before the closing body tag of your site." },
      { title: "Choose lead capture", body: "Decide whether to ask for contact details before opening the chat." },
      { title: "Watch results", body: "See opens, clicks and captured leads in the widget page." },
    ],
    useCases: [
      { title: "Landing pages", body: "Give ad traffic a faster path than a form: one tap to a real conversation." },
      { title: "Ecommerce product pages", body: "Answer sizing, stock and delivery questions where the shopper is deciding." },
      { title: "Offline to online", body: "Put the QR code on print and packaging to start chats from the real world." },
    ],
    faqs: [
      { q: "Will the widget slow my site down?", a: "The script is small, loads asynchronously and is cached, so it doesn't block your page from rendering." },
      { q: "Can I show it only on certain pages?", a: "The widget loads wherever you add the script. Add it only to the templates or pages where you want it to appear." },
      { q: "Do visitors need WhatsApp installed?", a: "On mobile the button opens the WhatsApp app; on desktop it opens WhatsApp Web or the desktop app." },
      { q: "What happens to captured leads?", a: "They are added to your contacts with the widget as their source, ready for a flow, a deal or a broadcast." },
    ],
    related: ["shared-inbox", "chat-flow-builder", "sales-pipeline"],
  },
  {
    slug: "templates",
    navLabel: "Template Manager",
    icon: FileText,
    tagline: "Create, submit and track WhatsApp templates in one place",
    metaTitle: "WhatsApp Message Template Manager",
    metaDescription: "Create WhatsApp message templates with variables, buttons and media, submit them to Meta and track approval status. Start from a library of ready-made templates.",
    keywords: ["WhatsApp message templates", "WhatsApp template approval", "WhatsApp template manager", "WhatsApp utility templates"],
    h1: "Message templates without the back-and-forth",
    lead: "Write a template, preview it exactly as customers will see it, submit it to Meta and watch its status update. Start from proven examples and get to approved faster.",
    visual: "templates",
    benefits: [
      { icon: FileText, title: "Live preview", body: "See the header, body, footer and buttons as a WhatsApp bubble while you type." },
      { icon: Layers, title: "Variables with examples", body: "Add {{1}}-style variables and sample values — the same examples Meta reviews when approving your template." },
      { icon: MousePointerClick, title: "Buttons and media", body: "Quick replies, URL and phone buttons, copy-code and one-time-password buttons, plus image, video and document headers." },
      { icon: Sparkles, title: "Template library", body: "Begin with ready-made utility, marketing and authentication templates and adapt the wording to your business." },
      { icon: Bell, title: "Status you can trust", body: "Pending, approved, rejected and paused states update from Meta's notifications and a periodic sync." },
      { icon: ShieldCheck, title: "Guardrails before you submit", body: "We validate variables, lengths and button rules up front so fewer templates bounce back." },
    ],
    steps: [
      { title: "Pick a category", body: "Utility, marketing or authentication — each has different rules and pricing on WhatsApp." },
      { title: "Write and preview", body: "Compose the message, add variables with examples and buttons if needed." },
      { title: "Submit to Meta", body: "One click sends it for review; you'll see the status as soon as Meta responds." },
      { title: "Use it everywhere", body: "Approved templates appear in the inbox, broadcasts, flows and integrations." },
    ],
    useCases: [
      { title: "Order lifecycle", body: "Confirmation, shipped, out for delivery and delivered — all as utility templates." },
      { title: "Reminders", body: "Appointments, renewals and payments due, personalised with the customer's details." },
      { title: "Verification", body: "One-time passwords with a copy-code button." },
    ],
    faqs: [
      { q: "How long does approval take?", a: "Meta usually reviews templates quickly, but timing varies. The status is shown in the dashboard as soon as Meta updates it." },
      { q: "Why was my template rejected?", a: "Common reasons are promotional wording in a utility template, missing variable examples or unclear content. The rejection reason is shown so you can edit and resubmit." },
      { q: "Can I edit an approved template?", a: "Meta limits edits to approved templates. Create a new version for bigger changes." },
      { q: "Can I send templates from the API?", a: "Yes. Send approved templates through the REST API with your variables filled in." },
    ],
    related: ["broadcasts", "shared-inbox", "integrations-api"],
  },
  {
    slug: "analytics",
    navLabel: "Conversation Analytics",
    icon: BarChart3,
    tagline: "See volume, response time and team workload at a glance",
    metaTitle: "WhatsApp Conversation Analytics & Reports",
    metaDescription: "Track messages, first-response time, delivery and read rates, campaign performance and agent workload for your WhatsApp Business conversations.",
    keywords: ["WhatsApp analytics", "WhatsApp response time", "WhatsApp campaign report", "WhatsApp agent performance"],
    h1: "Analytics that show how your WhatsApp desk is really doing",
    lead: "Know how many conversations you get, how quickly you reply, whether your messages are delivered and read, and who on the team is carrying the load.",
    visual: "analytics",
    benefits: [
      { icon: BarChart3, title: "Volume over time", body: "Messages received and sent per day, plus new conversations and new contacts." },
      { icon: Clock, title: "First-response time", body: "The average time it takes to answer a customer's first message." },
      { icon: Send, title: "Delivery funnel", body: "Sent, delivered, read and failed for outgoing messages, with the percentages that matter." },
      { icon: Users, title: "Team activity", body: "Messages and conversations handled per agent so workloads are visible and fair." },
      { icon: Megaphone, title: "Campaign reports", body: "Per-campaign delivery, reads, replies and failures with reasons." },
      { icon: TrendingUp, title: "Sales reports", body: "Revenue won, win rate and pipeline forecast from the same dashboard." },
    ],
    steps: [
      { title: "Work as usual", body: "Analytics are built from real conversations — nothing to instrument." },
      { title: "Choose a range", body: "Look at the last 7, 30 or 90 days." },
      { title: "Spot the gaps", body: "Find slow hours, overloaded agents or campaigns with poor delivery." },
      { title: "Act", body: "Adjust assignment rules, hours or content and watch the numbers move." },
    ],
    useCases: [
      { title: "Support managers", body: "Set response-time targets and coach the team with real numbers." },
      { title: "Marketing", body: "Compare campaigns by delivery, reads and replies to learn what works." },
      { title: "Founders", body: "Keep one eye on volume, response and revenue without a BI tool." },
    ],
    faqs: [
      { q: "How is first-response time measured?", a: "From a customer's first message in a conversation to the first reply sent by an agent, bot or flow." },
      { q: "Can I export the data?", a: "Contacts and deals export to CSV, and the REST API and webhooks let you send events to your own analytics tools." },
      { q: "Is data real-time?", a: "Delivery and read states update as WhatsApp reports them, typically within seconds." },
      { q: "Do analytics include conversations handled by the AI agent?", a: "Yes. Messages sent by bots, flows, the AI agent and agents are all counted, and you can tell them apart in the inbox." },
    ],
    related: ["shared-inbox", "broadcasts", "sales-pipeline"],
  },
  {
    slug: "integrations-api",
    navLabel: "Integrations & API",
    icon: Plug,
    tagline: "Connect your store, payments, Slack and your own systems",
    metaTitle: "WhatsApp Integrations, REST API & Webhooks",
    metaDescription: "Connect Shopify, WooCommerce, Razorpay, Stripe and Slack, or use the REST API and signed webhooks to send messages and react to events from your own systems.",
    keywords: ["WhatsApp API integration", "Shopify WhatsApp", "WooCommerce WhatsApp", "WhatsApp webhooks REST API"],
    h1: "Connect WhatsApp to the tools you already run on",
    lead: "Trigger messages from store orders and payments, notify your team in Slack, and use a documented REST API and signed webhooks to integrate anything else.",
    visual: "integrations",
    benefits: [
      { icon: Plug, title: "Store and payment events", body: "Order placed, paid, shipped or cancelled from Shopify and WooCommerce; payment captured or failed from Razorpay and Stripe." },
      { icon: MessageSquareReply, title: "Event → template", body: "Map each event to an approved template with variables filled from the event, so customers get the right message automatically." },
      { icon: Bell, title: "Slack notifications", body: "Post new conversations, captured leads, failed messages, won deals and received payments to a channel." },
      { icon: KeyRound, title: "REST API with keys", body: "Send messages and templates, upsert contacts and track events with scoped, revocable API keys." },
      { icon: Webhook, title: "Signed outbound webhooks", body: "Receive message, contact, campaign, deal and payment events at your URL, signed with HMAC-SHA256." },
      { icon: ShieldCheck, title: "Verified, not trusted", body: "Inbound provider events are verified with the provider's signature, and endpoints that keep failing are disabled automatically." },
    ],
    steps: [
      { title: "Choose an integration", body: "Pick Shopify, WooCommerce, Razorpay, Stripe, Slack or a generic webhook." },
      { title: "Paste the hook URL", body: "Add the URL we give you to the provider and set the signing secret." },
      { title: "Map events to templates", body: "Decide which message goes out for each event." },
      { title: "Go live", body: "Events flow in, contacts are created or updated and messages go out." },
    ],
    useCases: [
      { title: "Ecommerce stores", body: "Order confirmations, shipping updates and abandoned checkout nudges on WhatsApp." },
      { title: "Custom software", body: "Send an OTP, an invoice or a status update from your own backend with one API call." },
      { title: "Operations", body: "Pipe every new lead or payment into Slack or your data warehouse." },
    ],
    faqs: [
      { q: "Is there an API rate limit?", a: "API keys are limited to a generous number of requests per minute. The limit is shown in Settings → Developer alongside the key." },
      { q: "How do I verify your webhooks?", a: "Every delivery carries an X-LFG-Signature header — the HMAC-SHA256 of the raw body using your endpoint's secret. The docs include an example." },
      { q: "Can I connect Zapier, Make or n8n?", a: "Yes. Use the generic webhook integration or the REST API from any automation platform that can make HTTP requests." },
      { q: "Where can I see the API reference?", a: "In the documentation, which lists every public endpoint with example requests." },
    ],
    related: ["payments", "templates", "chat-flow-builder"],
  },
];

export const featureBySlug = (slug: string) => FEATURES.find((f) => f.slug === slug);
