import { SITE } from "./config";
import type { Block } from "./seo";

export type LegalDoc = { slug: string; title: string; metaDescription: string; summary: string; body: Block[] };

const CO = SITE.legalName;
const MAIL = SITE.supportEmail;

/**
 * NOTE FOR THE BUSINESS: these texts are a solid, product-accurate starting point but are not legal advice. Have a lawyer review them
 * (especially liability, governing law, refunds and the grievance officer details) before relying on them.
 */
export const LEGAL: LegalDoc[] = [
  {
    slug: "privacy",
    title: "Privacy Policy",
    metaDescription: `How ${CO} collects, uses, shares and protects personal data when you use LeadForGrow, and the choices and rights you have.`,
    summary: "What we collect, why we collect it, who we share it with and how you can control it.",
    body: [
      { type: "p", text: `This policy explains how **${CO}** ("**${SITE.name}**", "we", "us") handles personal data when you visit our website or use the LeadForGrow service. It applies under India's Digital Personal Data Protection Act, 2023, the Information Technology Act, 2000 and, where relevant, the EU/UK GDPR.` },
      { type: "h2", text: "1. Two roles: our data and your customers' data" },
      { type: "ul", items: ["**Account data** — information about you and your team members that we collect to run your account. For this we decide why and how it is used.", "**Workspace data** — contacts, conversations, templates and files your business puts into LeadForGrow. For this we process data **on your behalf** and under your instructions; you decide why it is collected and are responsible for having a lawful basis and consent to message your customers."] },
      { type: "h2", text: "2. What we collect" },
      { type: "table", head: ["Category", "Examples", "Why"], rows: [["Account", "Name, work email, company name, role, hashed password, login times", "Create and secure your account; communicate with you"], ["Workspace data", "Contact names and phone numbers, WhatsApp messages and media, tags, deals, templates, knowledge-base content", "Provide the service you asked for"], ["Billing", "Business name, GSTIN, address, invoices, payment status and Razorpay identifiers. Card, UPI and bank details are entered on Razorpay and never reach us", "Take payment, issue GST invoices, meet tax obligations"], ["Technical", "IP address, browser type, timestamps and error logs", "Keep the service secure, reliable and abuse-free"], ["Website forms", "Name, email, phone, company and message from the contact form; email for the newsletter", "Respond to enquiries and send updates you asked for"]] },
      { type: "h2", text: "3. How we use it" },
      { type: "ul", items: ["To provide, maintain and improve LeadForGrow", "To authenticate you and prevent fraud and abuse", "To process payments and send invoices and service notices", "To provide support", "To comply with legal obligations", "To send product news you have opted into — you can unsubscribe at any time"] },
      { type: "p", text: "We do not sell personal data, and we do not use the content of your customers' conversations for advertising." },
      { type: "h2", text: "4. Who we share data with (sub-processors)" },
      { type: "p", text: "We use trusted providers to run the service. They may process data outside India and are bound by contractual obligations appropriate to their role." },
      { type: "table", head: ["Provider", "Purpose"], rows: [["Meta Platforms (WhatsApp Business Platform)", "Sending and receiving WhatsApp messages through your connected number"], ["Razorpay", "Payment processing for LeadForGrow plans, and for payment links if you connect your own Razorpay account"], ["Anthropic", "Generating AI replies, only when your workspace enables the AI agent or an AI step"], ["Vercel", "Hosting the website and dashboard front end"], ["Railway", "Hosting the application servers and database"], ["Resend", "Sending transactional email such as invitations, password resets and receipts"]] },
      { type: "p", text: "We may also disclose information if required by law, to protect rights and safety, or in connection with a business transfer, in which case we will tell you and the acquirer must honour this policy." },
      { type: "h2", text: "5. Retention" },
      { type: "p", text: "We keep account and workspace data while your account is active. After you delete your workspace we remove workspace data within a reasonable period, except records we must keep by law (for example tax invoices, kept for the period required under Indian law). Server logs are kept for a limited period." },
      { type: "h2", text: "6. Security" },
      { type: "p", text: "We use encryption in transit, encrypt stored credentials (WhatsApp tokens, AI keys, payment keys), hash passwords, verify webhook signatures and restrict access by role. See our [Security page](/security). No system is perfectly secure; we will notify affected users and authorities where required if a breach occurs." },
      { type: "h2", text: "7. Your rights" },
      { type: "p", text: `You may ask to access, correct, update or erase your personal data, withdraw consent, or nominate someone to exercise these rights on your behalf. If you are in the EU/UK you may also object to or restrict certain processing and request portability. Email **${MAIL}** and we will respond within the time required by law. If you are a contact of one of our customers, please contact that business first — they control your data — and we will support them in responding.` },
      { type: "h2", text: "8. Cookies" },
      { type: "p", text: "See our [Cookie Policy](/cookies)." },
      { type: "h2", text: "9. Children" },
      { type: "p", text: "LeadForGrow is for businesses and is not directed at children. We do not knowingly collect personal data from children." },
      { type: "h2", text: "10. Changes" },
      { type: "p", text: "We will post updates here and, for material changes, notify account holders by email or in the dashboard." },
      { type: "h2", text: "11. Contact and grievance redressal" },
      { type: "p", text: `${CO}${SITE.address ? `, ${SITE.address}` : ""}. Email: **${MAIL}**. Grievances about the handling of personal data can be sent to the same address, marked "Grievance Officer"; we aim to acknowledge within 48 hours and resolve within 30 days.` },
    ],
  },
  {
    slug: "terms",
    title: "Terms of Service",
    metaDescription: `The agreement between ${CO} and customers who use LeadForGrow: accounts, acceptable use, fees, data, AI features, liability and more.`,
    summary: "The rules for using LeadForGrow, what you can expect from us and what we expect from you.",
    body: [
      { type: "p", text: `These terms are an agreement between **${CO}** ("we", "us") and the business or person who creates a LeadForGrow account ("you"). By creating an account or using the service you accept them. If you accept on behalf of a company, you confirm you are authorised to do so.` },
      { type: "h2", text: "1. The service" },
      { type: "p", text: "LeadForGrow is software for managing WhatsApp Business conversations, automation, campaigns, sales and payments. It works with the WhatsApp Business Platform provided by Meta. We are an independent company and are **not affiliated with, endorsed by or sponsored by WhatsApp or Meta**." },
      { type: "h2", text: "2. Your account" },
      { type: "ul", items: ["Provide accurate information and keep it up to date", "Keep credentials confidential and tell us promptly about unauthorised use", "You are responsible for activity under your workspace, including by team members you invite"] },
      { type: "h2", text: "3. Using WhatsApp responsibly" },
      { type: "p", text: "You must follow the [WhatsApp Business Terms of Service](https://www.whatsapp.com/legal/business-terms), the WhatsApp Business Messaging and Commerce Policies and applicable law. In particular:" },
      { type: "ul", items: ["Only message people who have **opted in** to hear from you on WhatsApp, and honour opt-outs", "Do not send spam, unlawful, deceptive, harassing or prohibited content", "Do not use the service for prohibited categories under Meta's policies", "You are responsible for your message templates and for Meta's charges and decisions about your account, including limits, quality rating and suspension"] },
      { type: "h2", text: "4. Acceptable use" },
      { type: "p", text: "Do not misuse the service: no attempts to breach security, overload or reverse engineer it, no illegal activity, no infringing others' rights, and no reselling or white-labelling the service except under a written partner agreement." },
      { type: "h2", text: "5. Plans, fees and taxes" },
      { type: "ul", items: ["Paid plans are **prepaid** for the period you choose (1, 3 or 12 months) and do not renew automatically", "Prices are shown in Indian Rupees **before GST**; 18% GST (or the rate applicable at the time) is added at checkout", "Changing to a different plan during a paid period credits the unused value of the current plan, as shown before you pay", "If a paid plan ends without renewal, the workspace moves to the free plan after a short grace period; your data is kept but plan limits apply", "Meta's charges for WhatsApp messages and any fees charged by Razorpay on payments you collect from your own customers are separate from our fees and are your responsibility"] },
      { type: "p", text: "See our [Refund & Cancellation Policy](/refund-policy) for cancellation and refunds." },
      { type: "h2", text: "6. Your data" },
      { type: "p", text: "You own your workspace data. You give us permission to process it only to provide and support the service, as described in our [Privacy Policy](/privacy). You are responsible for having the rights and consents needed to upload it and to message your contacts. You can export contacts and deals, and you can ask us to delete your workspace." },
      { type: "h2", text: "7. AI features" },
      { type: "p", text: "AI-generated replies may be inaccurate or incomplete. You are responsible for configuring the AI agent, reviewing its output and deciding where it is appropriate to use. Do not rely on it for legal, medical, financial or other high-stakes advice to your customers without human review." },
      { type: "h2", text: "8. Third-party services" },
      { type: "p", text: "The service depends on third parties such as Meta, Razorpay, Anthropic and hosting providers. We are not responsible for their availability, changes or decisions, though we will work with you to resolve issues." },
      { type: "h2", text: "9. Availability and support" },
      { type: "p", text: "We work to keep the service available but do not guarantee uninterrupted operation. We may perform maintenance and will try to give notice of planned downtime. Check [system status](/status)." },
      { type: "h2", text: "10. Suspension and termination" },
      { type: "p", text: "You may stop using the service at any time. We may suspend or terminate access if you breach these terms, put the service or others at risk, or where required by law or by Meta. Where reasonable we will tell you first." },
      { type: "h2", text: "11. Disclaimers" },
      { type: "p", text: "The service is provided \"as is\" and \"as available\". To the extent permitted by law, we disclaim all warranties, including merchantability, fitness for a particular purpose and non-infringement." },
      { type: "h2", text: "12. Limitation of liability" },
      { type: "p", text: "To the extent permitted by law, we are not liable for indirect, incidental, special or consequential damages, or loss of profits, revenue or data. Our total liability for any claim relating to the service is limited to the fees you paid us in the twelve months before the event giving rise to the claim. Nothing limits liability that cannot be limited by law." },
      { type: "h2", text: "13. Indemnity" },
      { type: "p", text: "You will indemnify us against third-party claims arising from your content, your messaging practices or your breach of these terms or of Meta's policies." },
      { type: "h2", text: "14. Governing law" },
      { type: "p", text: "These terms are governed by the laws of India. Courts having jurisdiction at the location of our registered office have exclusive jurisdiction, subject to any mandatory rights you have." },
      { type: "h2", text: "15. Changes and contact" },
      { type: "p", text: `We may update these terms; for material changes we will give notice. Continued use after the effective date means you accept them. Questions: **${MAIL}**.` },
    ],
  },
  {
    slug: "refund-policy",
    title: "Refund & Cancellation Policy",
    metaDescription: "How to cancel LeadForGrow, when refunds apply, how failed or duplicate payments are handled and how long refunds take.",
    summary: "Plans are prepaid and don't auto-renew. Here's how cancellation and refunds work.",
    body: [
      { type: "h2", text: "Cancellation" },
      { type: "ul", items: ["Plans are prepaid and **do not renew automatically**, so there is nothing to cancel to avoid a future charge", "Your plan stays active until the end of the period you paid for", "You can delete your workspace at any time by contacting us"] },
      { type: "h2", text: "Refunds" },
      { type: "table", head: ["Situation", "What happens"], rows: [["You paid, but the payment failed or was charged twice", "Failed and duplicate payments are refunded to the original payment method. Razorpay normally completes these within 5–7 business days. Contact us if it takes longer."], ["You are unhappy within 7 days of your **first** paid purchase", "Contact us and we'll refund your payment in full, provided the account hasn't broken our Terms or Meta's policies."], ["You want to leave partway through a paid period", "We don't refund the unused part of a period after the first 7 days."], ["You move to a different plan", "The unused value of your current plan is credited toward the new plan at checkout, so you don't pay twice for the same time."], ["A billing error on our side", "We correct it and refund the difference."]] },
      { type: "h2", text: "What isn't refundable" },
      { type: "ul", items: ["Charges made by Meta for WhatsApp messages, which are billed by Meta", "Fees charged by Razorpay or others on payments you collected from your own customers", "GST that has already been remitted, except where the underlying payment is refunded"] },
      { type: "h2", text: "How to ask for a refund" },
      { type: "p", text: `Email **${MAIL}** from your account email with your invoice number and the reason. We reply within 2 business days. Approved refunds are issued to the original payment method and usually reach you within 5–10 business days, depending on your bank.` },
    ],
  },
  {
    slug: "cookies",
    title: "Cookie Policy",
    metaDescription: `What cookies and similar storage ${CO} uses on the LeadForGrow website and dashboard, and how to control them.`,
    summary: "We keep this simple: only what's needed to sign you in and remember your preferences.",
    body: [
      { type: "p", text: "Cookies and similar technologies (such as your browser's local storage) are small pieces of data stored on your device. Here is what LeadForGrow uses." },
      { type: "table", head: ["Purpose", "What we store", "Duration"], rows: [["Sign-in (essential)", "Session tokens that keep you signed in to the dashboard", "Until you sign out or the session expires"], ["Preferences (essential)", "Your light or dark theme choice", "Until you clear it"], ["Security (essential)", "Short-lived data used to protect forms and rate-limit abuse", "Short"]] },
      { type: "p", text: "We do not use advertising cookies. If we add analytics or other optional technologies in future, we will update this page and ask for your consent where the law requires it." },
      { type: "h2", text: "Third-party content" },
      { type: "p", text: "When you pay, Razorpay's checkout may set its own cookies to process the transaction and prevent fraud; see Razorpay's policies. Embedded fonts are served from our own domain." },
      { type: "h2", text: "Your choices" },
      { type: "p", text: "You can clear stored data or block cookies in your browser settings. Blocking essential storage will stop you from signing in." },
    ],
  },
  {
    slug: "security",
    title: "Security",
    metaDescription: `How ${CO} protects LeadForGrow customer data: encryption, access control, webhook verification, tenant isolation and responsible disclosure.`,
    summary: "The practical measures we take to protect your workspace and your customers' data.",
    body: [
      { type: "p", text: "Your conversations and contacts are among your business's most sensitive data. This page describes the controls we operate today." },
      { type: "h2", text: "Data protection" },
      { type: "ul", items: ["**Encryption in transit** using TLS for the website, dashboard and API", "**Credentials encrypted at rest** — WhatsApp access tokens, app secrets, AI keys, integration secrets and payment keys are encrypted before they are stored, and are never shown again in full", "**Passwords are hashed** with a modern algorithm; we can't read them", "**Card and UPI details never touch our servers** — payments are handled by Razorpay"] },
      { type: "h2", text: "Access control" },
      { type: "ul", items: ["Role-based access (owner, admin, agent, viewer) checked on every request, so removing someone takes effect immediately", "Every workspace's data is isolated from every other's", "Sessions use short-lived tokens with refresh and can be ended by changing your password", "API keys are hashed, shown once and can be revoked at any time"] },
      { type: "h2", text: "Application security" },
      { type: "ul", items: ["Inbound WhatsApp and integration webhooks are accepted only if their **signature verifies**", "Outbound webhooks are signed with HMAC-SHA256, and requests to private or internal network addresses are blocked", "Rate limiting on sign-in, forms and APIs", "Input validation and constrained file uploads", "CSV exports neutralise spreadsheet formulas"] },
      { type: "h2", text: "Operations" },
      { type: "ul", items: ["Hosted on reputable cloud providers that maintain their own certifications", "Managed database with backups", "Health monitoring and a public [status page](/status)"] },
      { type: "callout", tone: "info", title: "Independent audits", text: "We have not yet completed an independent certification such as SOC 2 or ISO 27001 for LeadForGrow itself. If your organisation needs a security questionnaire or a data processing agreement, contact us." },
      { type: "h2", text: "Report a vulnerability" },
      { type: "p", text: `If you believe you've found a security issue, email **${MAIL}** with details. Please give us reasonable time to fix it before disclosing it publicly, and avoid accessing other people's data. We acknowledge reports promptly and appreciate responsible research.` },
    ],
  },
  {
    slug: "compliance",
    title: "Compliance",
    metaDescription: `How LeadForGrow supports compliance with WhatsApp Business policies, India's DPDP Act, GDPR and GST invoicing requirements.`,
    summary: "How the product helps you meet WhatsApp, data-protection and tax obligations.",
    body: [
      { type: "h2", text: "WhatsApp Business policies" },
      { type: "p", text: "LeadForGrow uses the official WhatsApp Business Platform. The product is built around its rules: message templates for business-initiated conversations, the 24-hour customer service window, opt-out handling and template category rules. You remain responsible for obtaining opt-in and for what you send." },
      { type: "h2", text: "India — DPDP Act, 2023 and IT Act, 2000" },
      { type: "ul", items: ["We collect personal data for stated purposes and describe them in our [Privacy Policy](/privacy)", "You can ask us to access, correct or erase your data and to withdraw consent", "We take reasonable security safeguards and will report breaches as the law requires", `A grievance channel is available at ${MAIL}`] },
      { type: "h2", text: "GDPR and UK GDPR" },
      { type: "p", text: "For customers who are subject to GDPR, we act as your **processor** for workspace data. We can provide a data processing agreement on request, list our sub-processors (see the Privacy Policy) and support your data-subject requests. International transfers rely on appropriate safeguards." },
      { type: "h2", text: "GST invoicing" },
      { type: "p", text: "Every paid plan generates a tax invoice with a sequential number, our GSTIN (when configured), your billing details and a CGST + SGST or IGST breakup based on the place of supply. Add your GSTIN under Billing details to claim input tax credit." },
      { type: "h2", text: "Payments" },
      { type: "p", text: "Payments are processed by Razorpay, which is PCI DSS compliant. We do not store your card, UPI or bank credentials." },
      { type: "h2", text: "Need something specific?" },
      { type: "p", text: `Contact **${MAIL}** for a security questionnaire, a data processing agreement or other compliance documents.` },
    ],
  },
  {
    slug: "accessibility",
    title: "Accessibility",
    metaDescription: `${CO}'s commitment to making the LeadForGrow website and dashboard usable by everyone, and how to report a problem.`,
    summary: "We aim for a site and dashboard that everyone can use.",
    body: [
      { type: "p", text: "We want everyone to be able to use LeadForGrow, including people who use screen readers, keyboards, zoom or high-contrast settings. We aim to follow the Web Content Accessibility Guidelines (WCAG) 2.1 level AA." },
      { type: "h2", text: "What we do" },
      { type: "ul", items: ["Semantic headings, landmarks and labelled form fields", "Keyboard access to menus, dialogs and forms", "Visible focus states and sufficient colour contrast in both the light and dark themes", "Respect for the 'reduce motion' setting", "Text alternatives for meaningful icons"] },
      { type: "h2", text: "Known limitations" },
      { type: "ul", items: ["The pipeline board supports drag and drop; the same changes can be made from the deal dialog using the Stage field, which works with a keyboard", "The visual flow builder canvas is mouse-oriented; we are working on better keyboard support"] },
      { type: "h2", text: "Tell us about a problem" },
      { type: "p", text: `If something isn't accessible to you, email **${MAIL}** with the page and what went wrong. We'll respond within a few business days and work on a fix.` },
    ],
  },
];

export const legalBySlug = (slug: string) => LEGAL.find((l) => l.slug === slug);
