"""whatsapp platform

Revision ID: 0002
Revises: 5beb8a9a9f11
Create Date: 2026-09-20 02:11:53.610714

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: Union[str, None] = '5beb8a9a9f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('integrations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('credentials_enc', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('hook_token', sa.String(length=48), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', name='uq_integrations_tenant_provider')
    )
    op.create_index(op.f('ix_integrations_hook_token'), 'integrations', ['hook_token'], unique=True)
    op.create_index(op.f('ix_integrations_tenant_id'), 'integrations', ['tenant_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_tenant_id'), 'knowledge_sources', ['tenant_id'], unique=False)
    op.create_table('outbound_webhooks',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('secret_enc', sa.Text(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_status', sa.String(length=64), nullable=True),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_webhooks_tenant_id'), 'outbound_webhooks', ['tenant_id'], unique=False)
    op.create_table('segments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_tenant_id'), 'segments', ['tenant_id'], unique=False)
    op.create_table('team_invites',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_invites_tenant_id'), 'team_invites', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_team_invites_token_hash'), 'team_invites', ['token_hash'], unique=True)
    op.create_table('webhook_ingress',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('event_key', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_index(op.f('ix_webhook_ingress_tenant_id'), 'webhook_ingress', ['tenant_id'], unique=False)
    op.create_table('whatsapp_accounts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('waba_id', sa.String(length=64), nullable=False),
    sa.Column('phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('display_phone_number', sa.String(length=32), nullable=True),
    sa.Column('verified_name', sa.String(length=200), nullable=True),
    sa.Column('quality_rating', sa.String(length=16), nullable=True),
    sa.Column('messaging_limit', sa.String(length=32), nullable=True),
    sa.Column('name_status', sa.String(length=32), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('app_secret_enc', sa.Text(), nullable=True),
    sa.Column('webhook_key', sa.String(length=48), nullable=False),
    sa.Column('verify_token', sa.String(length=64), nullable=False),
    sa.Column('connection_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_webhook_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_send_count', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number_id', name='uq_whatsapp_accounts_phone_number_id')
    )
    op.create_index(op.f('ix_whatsapp_accounts_tenant_id'), 'whatsapp_accounts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_accounts_webhook_key'), 'whatsapp_accounts', ['webhook_key'], unique=True)
    op.create_table('widgets',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('public_key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=False),
    sa.Column('prefill_message', sa.String(length=500), nullable=False),
    sa.Column('cta_text', sa.String(length=60), nullable=False),
    sa.Column('brand_color', sa.String(length=9), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('bottom_offset', sa.Integer(), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('collect_lead', sa.Boolean(), nullable=False),
    sa.Column('allowed_domains', sa.JSON(), nullable=False),
    sa.Column('opens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('leads', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widgets_public_key'), 'widgets', ['public_key'], unique=True)
    op.create_index(op.f('ix_widgets_tenant_id'), 'widgets', ['tenant_id'], unique=False)
    op.create_table('contact_events',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_events_contact_id'), 'contact_events', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_events_tenant_id'), 'contact_events', ['tenant_id'], unique=False)
    op.create_index('ix_contact_events_tenant_name', 'contact_events', ['tenant_id', 'name'], unique=False)
    op.create_table('conversations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('inbox_status', sa.String(length=16), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('labels', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_preview', sa.String(length=300), nullable=True),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('free_entry_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'contact_id', name='uq_conversations_account_contact')
    )
    op.create_index(op.f('ix_conversations_contact_id'), 'conversations', ['contact_id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_index('ix_conversations_tenant_last_message', 'conversations', ['tenant_id', 'last_message_at'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', content)", persisted=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_chunks_fts', 'knowledge_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_knowledge_chunks_source_id'), 'knowledge_chunks', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_tenant_id'), 'knowledge_chunks', ['tenant_id'], unique=False)
    op.create_table('automation_executions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_node', sa.String(length=64), nullable=True),
    sa.Column('waiting_for', sa.String(length=16), nullable=True),
    sa.Column('wait_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['flow_id'], ['automation_flows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automation_exec_status_wait', 'automation_executions', ['status', 'wait_until'], unique=False)
    op.create_index(op.f('ix_automation_executions_contact_id'), 'automation_executions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_automation_executions_flow_id'), 'automation_executions', ['flow_id'], unique=False)
    op.create_index(op.f('ix_automation_executions_tenant_id'), 'automation_executions', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_id', sa.String(length=128), nullable=True),
    sa.Column('media_mime', sa.String(length=128), nullable=True),
    sa.Column('media_filename', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('wamid', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sender_type', sa.String(length=16), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('broadcast_id', sa.UUID(), nullable=True),
    sa.Column('callback_data', sa.String(length=512), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_index('ix_messages_wamid', 'messages', ['wamid'], unique=False)
    op.create_table('broadcast_recipients',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('broadcast_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('wamid', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_broadcast_recipients_broadcast_status', 'broadcast_recipients', ['broadcast_id', 'status'], unique=False)
    op.create_index(op.f('ix_broadcast_recipients_tenant_id'), 'broadcast_recipients', ['tenant_id'], unique=False)
    op.create_index('ix_broadcast_recipients_wamid', 'broadcast_recipients', ['wamid'], unique=False)
    op.add_column('broadcasts', sa.Column('account_id', sa.UUID(), nullable=True))
    op.add_column('broadcasts', sa.Column('variable_mapping', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('broadcasts', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('broadcasts', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('broadcasts', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('broadcasts', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('broadcasts', sa.Column('read', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('broadcasts', sa.Column('replied', sa.Integer(), nullable=False, server_default='0'))
    op.create_foreign_key('fk_broadcasts_account_id', 'broadcasts', 'whatsapp_accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.add_column('custom_replies', sa.Column('match_type', sa.String(length=16), server_default='contains', nullable=False))
    op.add_column('custom_replies', sa.Column('flow_id', sa.UUID(), nullable=True))
    op.add_column('custom_replies', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    op.create_foreign_key('fk_custom_replies_flow_id', 'custom_replies', 'automation_flows', ['flow_id'], ['id'], ondelete='SET NULL')
    op.add_column('whatsapp_templates', sa.Column('account_id', sa.UUID(), nullable=True))
    op.add_column('whatsapp_templates', sa.Column('header_type', sa.String(length=16), nullable=False, server_default='none'))
    op.add_column('whatsapp_templates', sa.Column('header_text', sa.String(length=120), nullable=True))
    op.add_column('whatsapp_templates', sa.Column('header_example', sa.String(length=2000), nullable=True))
    op.add_column('whatsapp_templates', sa.Column('footer', sa.String(length=60), nullable=True))
    op.add_column('whatsapp_templates', sa.Column('buttons', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('whatsapp_templates', sa.Column('body_examples', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('whatsapp_templates', sa.Column('components', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('whatsapp_templates', sa.Column('quality_score', sa.String(length=16), nullable=True))
    op.add_column('whatsapp_templates', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_templates_account_id', 'whatsapp_templates', 'whatsapp_accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.execute("UPDATE whatsapp_templates SET status = 'draft' WHERE status = 'pending' AND meta_template_id IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_templates_account_id', 'whatsapp_templates', type_='foreignkey')
    op.drop_column('whatsapp_templates', 'last_synced_at')
    op.drop_column('whatsapp_templates', 'quality_score')
    op.drop_column('whatsapp_templates', 'components')
    op.drop_column('whatsapp_templates', 'body_examples')
    op.drop_column('whatsapp_templates', 'buttons')
    op.drop_column('whatsapp_templates', 'footer')
    op.drop_column('whatsapp_templates', 'header_example')
    op.drop_column('whatsapp_templates', 'header_text')
    op.drop_column('whatsapp_templates', 'header_type')
    op.drop_column('whatsapp_templates', 'account_id')
    op.drop_constraint('fk_custom_replies_flow_id', 'custom_replies', type_='foreignkey')
    op.drop_column('custom_replies', 'priority')
    op.drop_column('custom_replies', 'flow_id')
    op.drop_column('custom_replies', 'match_type')
    op.drop_constraint('fk_broadcasts_account_id', 'broadcasts', type_='foreignkey')
    op.drop_column('broadcasts', 'replied')
    op.drop_column('broadcasts', 'read')
    op.drop_column('broadcasts', 'error')
    op.drop_column('broadcasts', 'completed_at')
    op.drop_column('broadcasts', 'started_at')
    op.drop_column('broadcasts', 'scheduled_at')
    op.drop_column('broadcasts', 'variable_mapping')
    op.drop_column('broadcasts', 'account_id')
    op.drop_index('ix_broadcast_recipients_wamid', table_name='broadcast_recipients')
    op.drop_index(op.f('ix_broadcast_recipients_tenant_id'), table_name='broadcast_recipients')
    op.drop_index('ix_broadcast_recipients_broadcast_status', table_name='broadcast_recipients')
    op.drop_table('broadcast_recipients')
    op.drop_index('ix_messages_wamid', table_name='messages')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_automation_executions_tenant_id'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_flow_id'), table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_contact_id'), table_name='automation_executions')
    op.drop_index('ix_automation_exec_status_wait', table_name='automation_executions')
    op.drop_table('automation_executions')
    op.drop_index(op.f('ix_knowledge_chunks_tenant_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_source_id'), table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_fts', table_name='knowledge_chunks', postgresql_using='gin')
    op.drop_table('knowledge_chunks')
    op.drop_index('ix_conversations_tenant_last_message', table_name='conversations')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_contact_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_contact_events_tenant_name', table_name='contact_events')
    op.drop_index(op.f('ix_contact_events_tenant_id'), table_name='contact_events')
    op.drop_index(op.f('ix_contact_events_contact_id'), table_name='contact_events')
    op.drop_table('contact_events')
    op.drop_index(op.f('ix_widgets_tenant_id'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_public_key'), table_name='widgets')
    op.drop_table('widgets')
    op.drop_index(op.f('ix_whatsapp_accounts_webhook_key'), table_name='whatsapp_accounts')
    op.drop_index(op.f('ix_whatsapp_accounts_tenant_id'), table_name='whatsapp_accounts')
    op.drop_table('whatsapp_accounts')
    op.drop_index(op.f('ix_webhook_ingress_tenant_id'), table_name='webhook_ingress')
    op.drop_table('webhook_ingress')
    op.drop_index(op.f('ix_team_invites_token_hash'), table_name='team_invites')
    op.drop_index(op.f('ix_team_invites_tenant_id'), table_name='team_invites')
    op.drop_table('team_invites')
    op.drop_index(op.f('ix_segments_tenant_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_outbound_webhooks_tenant_id'), table_name='outbound_webhooks')
    op.drop_table('outbound_webhooks')
    op.drop_index(op.f('ix_knowledge_sources_tenant_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_integrations_tenant_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_hook_token'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
