"""add custom_replies table

Revision ID: 5beb8a9a9f11
Revises: 269842b9de0f
Create Date: 2026-09-18 17:11:21.297102

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5beb8a9a9f11'
down_revision: Union[str, None] = '269842b9de0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_replies',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=500), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('conversations_sent', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_replies_tenant_id'), 'custom_replies', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_replies_tenant_id'), table_name='custom_replies')
    op.drop_table('custom_replies')
    # ### end Alembic commands ###
